# Generated by Django 5.1 on 2024-09-28 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datauploader', '0002_alter_customuser_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='courserBy',
            new_name='courseBy',
        ),
    ]
