# Generated by Django 5.1 on 2024-09-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datauploader', '0005_alter_courses_coursename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='courseName',
            field=models.CharField(max_length=60),
        ),
    ]
