# Generated by Django 5.1 on 2024-09-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datauploader', '0007_enroledcourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
