# Generated by Django 5.1 on 2024-10-10 15:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datauploader', '0009_alter_customuser_city_alter_customuser_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='courseImg',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
